service: serverles-ex
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: dev
  httpApi:
    cors: true

plugins:
  - serverless-offline

functions:
    ${file(./routes/companyRoutes.yml):functions}