  functions:
    getAllCompanies: 
      handler: handlers/getAllCompaniesHandler.getAllCompanies
      events:
        - httpApi: 
            path: /companies
            method: get

    getCompanyById: 
      handler: handlers/getAllCompaniesByIdHandler.getCompanyById
      events:
        - httpApi: 
            path: /companies/{company_id}
            method: get
    
    createNewCompany:
      handler: handlers/createNewCompanyHandler.createNewCompany
      events:
        - httpApi: 
            path: /companies
            method: post
    
    editCompanyDetails:
      handler: handlers/editCompanyDetailsHandler.editCompanyDetails
      events:
        - httpApi:
            path: /companies/{company_id}
            method: PUT

    archiveCompany:
      handler: handlers/archiveCompanyHandler.archiveCompany
      events:
        - httpApi:
            path: /companies/{company_id}
            method: delete
    
    getTeamByCompany:
      handler: handlers/getTeamByCompanyHandler.getTeamByCompany
      events:
        - httpApi:
            path: /team/{company_name}/company
            method: get

    getTeamById:
      handler: handlers/getTeamByIdHandler.getTeamById
      events:
        - httpApi:
            path: /team/{id}
            method: get
    
    createTeam:
      handler: handlers/createTeamHandler.createTeam
      events:
        - httpApi:
            path: /team/{id}
            method: post
    
    editTeam:
      handler: handlers/editTeamHandler.editTeam
      events: 
        - httpApi:
            path: /team/{team_id}
            method: put

    archiveTeam:
      handler: handlers/archiveTeamHandler.archiveTeam
      events:
        - httpApi:
            path: /team/{team_id}
            method: delete
    
    getEmployeeByCompany:
      handler: handlers/getEmployeeByCompanyHandler.getEmployeeByCompany
      events:
        - httpApi: 
            path: /employee/{company_name}
            method: get

    getEmployeeByTeam:
      handler: handlers/getEmployeeByTeamHandler.getEmployeeByTeam
      events:
        -  httpApi:
            path: /employee/team/{team_name}
            method: get
    
    getEmployeeById:
      handler: handlers/getEmployeeByIdHandler.getEmployeeById
      events:
      - httpApi:
          path: /employee/id/{employee_id}
          method: get
    
    createEmployee:
      handler: handlers/createEmployeeHandler.createEmployee
      events: 
        - httpApi:
            path: /employee
            method: post

    editEmployee:
      handler: handlers/editEmployeeHandler.editEmployee
      events:
        - httpApi:
            path: /employee/{employee_id}
            method: put
    
    archiveEmployee:
      handler: handlers/archiveEmployeeHandler.archiveEmployee
      events:
        - httpApi:
            path: /employee/{employee_id}
            method: delete